version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: library_example
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # web:
  #   build: .
  #   container_name: my-node-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - mysql
  #   links:
  #     - mysql
